name: Sample test
on:
  workflow_dispatch:

jobs:
  test_echo:
    runs-on: ubuntu-slim
    steps:
      - name: test echo
        run: echo "This is sha ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
      - name: most needed outputs
        run: |
          echo "## Important values" >> $GITHUB_STEP_SUMMARY
          echo "Actor: $GITHUB_ACTOR" >> $GITHUB_STEP_SUMMARY
          echo "SHA: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
          echo "Branch: $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
